### ISSUE TITLE
Didn't receive message on discord.

### ISSUE THREAD

**Issue by divyanshu-in** [LeGitHubDeTai/github-to-discord#9]
here is the output log of action, it was successfully executed.

```
{
  url: '***',
  headers: { 'Content-Type': 'application/json', 'User-Agent': 'request' },
  body: '{"username":"Tai Studio","avatar_url":"https://raw.githubusercontent.com/LeGitHubDeTai/github-to-discord/main/icon.png","embeds":[{"title":"New Version release","description":"New Apk Released!","url":"https://github.com/Biscoitinhoo/millennium-for-reddit/releases/download/release/app-debug.apk","color":"58[14](https://github.com/Biscoitinhoo/millennium-for-reddit/runs/6133264137?check_suite_focus=true#step:3:14)783","fields":[{"name":"ChangeLog","value":""}],"author":{"name":"Tai Studio","url":"https://tai-studio.netlify.app/","icon_url":"https://tai-studio.netlify.app/img/logo/Tai_Studio.png"},"footer":{"text":"- Tai Studio © 2022 -","icon_url":"https://tai-studio.netlify.app/img/logo/Tai_Studio.png"},"thumbnail":{"url":"https://raw.githubusercontent.com/Biscoitinhoo/millennium-for-reddit/icon.png"}}]}'
}
{"embeds": ["0"]}
```

**Comment by LeGitHubDeTai** [comment]
hello, sorry for the delay.
can i see the repo you are trying to use github-to-discord on?

if not, your github repo must be public

**Comment by divyanshu-in** [comment]
https://github.com/Biscoitinhoo/millennium-for-reddit/ this is the repo I was using the action on, I replaced it though, this was the commit though https://github.com/Biscoitinhoo/millennium-for-reddit/commit/e986ed7cd8c19c8341296087c9f34743dfdeb202.

**Comment by MaxwellJung** [comment]
I think I'm having a similar issue. Action executes successfully, but I'm not seeing any message in the discord channel.

[yml file](https://github.com/MaxwellJung/ow1_emulator/blob/8f4197e92241205c689293e1eacb36c77879c4f7/.github/workflows/toDiscord.yml)

**Comment by LeGitHubDeTai** [comment]
please send me logs for debuging

**Comment by eythaann** [comment]
I'm not reciving updates now, It works before now I don't change nothing and it stop working.

```yml
  discord:
    needs: publish-release
    name: Send Announcement To Discord Server
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: LeGitHubDeTai/github-to-discord@main
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Seelen
          DISCORD_AVATAR: https://raw.githubusercontent.com/eythaann/Seelen-UI/master/documentation/images/logo_with_margins.png

          AUTHOR_NAME: eythaann
          AUTHOR_URL: "https://github.com/eythaann"
          AUTHOR_AVATAR: "https://avatars.githubusercontent.com/u/76607907?v=4"

          MESSAGE_TITLE: Seelen UI
          MESSAGE_DESCRIPTION: A new release of Seelen UI has been published
          MESSAGE_COLOR: 5814783

          SECTION_NAME: "ChangeLog"

          FOOTER_TEXT: "Seelen Inc."
          FOOTER_URL: "https://github.com/eythaann/seelen-ui"
 ```
